// IdeaProjects/travel/frontend/src/components/common/LoadingDots.tsx
export function LoadingDots() {
  return (
    <div className="inline-flex items-center gap-1" role="status" aria-live="polite" aria-label="???">
      <span className="h-2 w-2 animate-bounce rounded-full bg-sky-400 [animation-delay:-0.3s]" />
      <span className="h-2 w-2 animate-bounce rounded-full bg-sky-400 [animation-delay:-0.15s]" />
      <span className="h-2 w-2 animate-bounce rounded-full bg-sky-400" />
    </div>
  )
}

// IdeaProjects/travel/frontend/src/components/common/LoadingDots.vue
<template>
  <div class="flex gap-1">
    <span class="w-2 h-2 bg-stone-400 rounded-full animate-bounce" style="animation-delay: 0ms" />
    <span class="w-2 h-2 bg-stone-400 rounded-full animate-bounce" style="animation-delay: 150ms" />
    <span class="w-2 h-2 bg-stone-400 rounded-full animate-bounce" style="animation-delay: 300ms" />
  </div>
</template>
