// IdeaProjects/travel/frontend/src/components/common/LoadingSpinner.vue
<template>
  <div class="flex items-center justify-center py-12">
    <div class="flex flex-col items-center gap-3">
      <div class="w-8 h-8 border-2 border-stone-200 border-t-stone-800 rounded-full animate-spin" />
      <p class="text-sm text-stone-500">{{ text || '加载中...' }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{ text?: string }>()
</script>

// IdeaProjects/travel/frontend/src/components/common/LoadingSpinner.tsx
export function LoadingSpinner() {
  return (
    <div className="flex items-center justify-center py-10" role="status" aria-live="polite">
      <div className="h-10 w-10 animate-spin rounded-full border-4 border-sky-100 border-t-sky-500" />
      <span className="sr-only">???</span>
    </div>
  )
}
